urls.py
from django.conf.urls.defaults import *
import settings
# from recipedia.myuser.forms import signin

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

# It handle serveral views through jQuery dialog interface
dialogurl = patterns('',
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'dialog/login.html'}, name="d_login"),
    url(r'^ingredient/insert\.html$', 'recipedia.forms.add_ingredient', name="add_ingredient_dlg"),
)
authurl = patterns('',
    (r'^$', 'recipedia.myuser.forms.signin', {'base_template_name': 'basepage.html'}),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}, name="n_login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'template_name': 'registration/logout.html', 'next_page': '/'}, name="n_logout"),
)
urlpatterns = patterns('',
    (r'^$', 'recipedia.views.index'),
    (r'^i18n/', include('django.conf.urls.i18n')),
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    (r'^accounts/', include(authurl)),
    (r'^dialog/', include(dialogurl)),
    (r'^recipe/insert\.html$', 'recipedia.views.create'),
    (r'^recipe/mine\.html$', 'recipedia.views.mine'),
    (r'^recipe/(?P<rpID>[0-9]+)/edit\.html$', 'recipedia.views.edit'),
    (r'^recipe/(?P<rpID>[0-9]+)/contentedit\.html$', 'recipedia.views.create_edit'),
    (r'^recipe/(?P<rpID>[0-9]+)/delete\.html$', 'recipedia.views.delete'),
    (r'^recipe/(?P<rpID>.*)/$', 'recipedia.views.view'),
    (r'^ingredient/insert\.html$', 'recipedia.forms.add_ingredient', {'nondialog': True}),
    url(r'^search/tag$', 'recipedia.views.search',{'lookup': 'tag'} , name="tag_search"),
    (r'^scrp/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + 'default/js/'}),
    url(r'^media1/images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT + 'classifieds/default/images/'}, name="c_media"),
    (r'^media1/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

forms.py
# from django.core.context_processors import csrf
# from django.core.files.uploadedfile import SimpleUploadedFile
# from django.core.urlresolvers import reverse
# from django.forms.models import inlineformset_factory
# from os import remove, path, mkdir
# from PIL import Image
# from tagging.forms import TagField
import shutil
# import tempfile
from datetime import datetime, date, timedelta
from django import forms
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm, Textarea
from django.forms.widgets import RadioSelect, HiddenInput, Select
from django.http import HttpResponseRedirect, HttpResponse, Http404, HttpResponseForbidden
from django.shortcuts import render_to_response, get_object_or_404
from django.template import Context, loader, RequestContext
from recipedia.models import Recipe, Ingredients, RecipeIngredients, RecipeCookmethods
from tagging.forms import TagField
# Hidden required fields should override it as "required=False" first and fill up custom value in views or unlying model
# To pass form validation, required field(s) in derived model shoul override as "required=False" here and set custom data in form save or model save method

class TermAndConditionForm(forms.Form):
    Agreed = forms.BooleanField()

class RecipeForm(ModelForm):
    name = forms.CharField(max_length=75)
    tag = TagField()
    full_photo = forms.ImageField(required=False)
    thumb_photo = forms.ImageField(required=False)
    activation_key = forms.CharField(max_length=40,required=False)
    # privacy =  models.PositiveSmallIntegerField(default=PRIVATE)
    class Meta:
        model = Recipe
        fields = ('name', 'tag','full_photo', 'thumb_photo', 'activation_key')
    class Media:
        js = (
            '/scrp/jquery.js',
            # 'scrp/tiny_mce/tiny_mce.js',
        )

class IngredientForm(ModelForm):
    name = forms.CharField(max_length=75)
    category = forms.CharField(max_length=75)
    measure = forms.CharField(max_length=15)
    full_photo = forms.ImageField(required=False)
    thumb_photo = forms.ImageField(required=False)
    class Meta:
        model = Ingredients
        fields = ('name','category','measure','full_photo', 'thumb_photo')
    class Media:
        js = (
            '/scrp/jquery.js',
        )

class RecipeCookmethodForm(ModelForm):
    recipe = forms.IntegerField()
    cookmethod = forms.CharField(max_length=250, widget = \
            Textarea(attrs={'class': 'cooking', 'cols': 50, 'rows': 1})
            )
    class Meta:
        model = RecipeCookmethods
    class Media:
        js = (
            '/scrp/jquery.js',
        )

class RecipeIngredientForm(ModelForm):
    recipe = forms.IntegerField()
    ingredient = forms.IntegerField(widget=HiddenInput())
    ingrdname = forms.CharField(max_length=75)
    quantity = forms.DecimalField(max_digits=9,decimal_places=2)
    measure = forms.CharField(max_length=15)
    class Meta:
        model = RecipeIngredients
    class Media:
        js =  ('/scrp/jquery.js', '/scrp/jquery-ui.js', '/scrp/inc/jquery.hoverIntent.min.js', '/scrp/inc/jquery.metadata.js', '/scrp/inc/jquery.mb.flipText.js', '/scrp/inc/mbExtruder.js',
        )
        css = {'all': ('/scrp/css/mbExtruder.css',            
        ), 'screen': (settings.MEDIA_URL + 'theme/ui-lightness/ui-lightness.css', )}
    def clean_ingredient(self):
        data = self.cleaned_data['ingredient']
        return Ingredients.objects.get(pk=data)
    
#@login_required(login_url='/dialog/accounts/login/')
def add_ingredient(request, nondialog = False):
    if request.method == 'POST':
        form = IngredientForm(request.POST)
        if form.is_valid():
            form.save()
            form = Ingredients.objects.get(name=form.cleaned_data['name'])
            return render_to_response('view_ingredient.html', {'form': form}, context_instance=RequestContext(request))
    else:
        form = IngredientForm()
    return render_to_response('new_ingredient.html', {'form': form}, context_instance=RequestContext(request))

# -----------------------------------------------------------------------------------
# backup code for possible usage
@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():            
            rp = form.save(commit=False)
            data = form.cleaned_data
            rp.activation_key = activation_key(request)
            rp.ruser = request.user
            rp.save()
            create_thumb(rp)
            return HttpResponseRedirect(reverse('recipedia.views.edit', args=[rp.pk]))
    else:
        form = RecipeForm()
    return render_to_response('new_recipe.html', {'form': form}, context_instance=RequestContext(request))

templates/basepage.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-tw" xml:lang="zh-tw" > 
<head profile="http://gmpg.org/xfn/11">
  <meta http-equiv="content-type" content="multipart/alternative; charset=utf-8">
  <meta name="keywords" content="{% block page_keywords %}{% endblock %}">
  <link type="text/css" rel="stylesheet" media="all" href="{{ MEDIA_URL }}theme/citrus-mix/style.css" />
  {% block page_meta %}{% endblock %}
  {% block page_style %}{% endblock %}
  <title>{% block title %}{% endblock %}</title>
  {% block head_script %}{% endblock %}
</head>
{% block custom_bodytag %}<body>{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

templates/edit_recipe.html
{% extends "basepage.html" %}
{% load i18n %}
{% block page_meta %}{{ grpmedia|safe }}
<style type="text/css">
.selected_ingredient {background: #FFA0A0; margin: 0.2em; padding-left: 0.3em;}
.item-added {display: none;}
.extruder.right .text {
  background: url("/scrp/elements/red_op_50.png");
}
.extruder.right .content {
  background: url("/scrp/elements/red_op_50.png");
}

</style>
<script type="text/javascript">
    $(function(){
//        var vtop = 0;
        $(".MbExtruder").each(function() {
            $(this).buildMbExtruder({
                position:"right",
                width:300,
                positionFixed:false,
//                top:vtop,
                extruderOpacity:.6,
                onExtOpen:function(){},
                onExtContentLoad:function(){},
                onExtClose:function(){}
            });
//            vtop += 80;
        });
    });
</script>
<script type="text/javascript">
var para = {helper: 'clone',opacity: 0.35,cancel:'.item-added'};
var itemcount = 0;
var itemfilled = 0;
$(document).ready(function(){
    $(function() {
        $("#selected_item").selectable();
    });
    $(".ingredient").draggable(para);
    $("input[id$='ingrdname']").droppable({
        activeClass: 'ui-selected',
        hoverClass: 'ui-state-hover',
        drop: function(event, ui) {
            var name = ui.draggable.text();
            var val = ui.draggable.attr('value');
            var v1 = this.id.replace("ingrdname","ingredient");
            var v2 = this.id.replace("ingrdname","measure");
//               $( "<li></li>" ).text( name ).appendTo( this );
//            $("#selected_item > li").addClass('selected_ingredient');
            ui.draggable.addClass('item-added');
            $(".ui-draggable-dragging").remove();
            // alert(this.id + " : " + v1 + " : " + val);
            this.value = name;
//            alert(v1 + "/n"+ v2);
            $("#" + v1).attr('value', val);
            $("#" + v2).attr('value', ui.draggable.attr('data'));
            itemcount = $('input[id$="ingredient"][value]').length;
//            ++itemcount;
            $('#selected_item > span').text(itemcount + ' item(s) added');
        }
    });
    $(function() {
        $("#revert_selected_item").click(
            function() {
                $("#selected_item > li.ui-selected").each(
                function() {
                    var ing = $(this).text();
                    $( "#vegetable > li:contains('" + ing + "')").removeClass('item-added');
                    $( "#meat > li:contains('" + ing + "')").removeClass('item-added');
                    $(this).remove();
                    $("#selected_item > span").text($('#selected_item > .selected_ingredient').length.toString() + ' item(s) added');
                });
                return false;
        });
    });
//    itemcount = Number($('input[id$="-INITIAL_FORMS"]')[0].getAttribute('value'));
    if ($('input[id$="ingredient"][value]').length) {
       $("#selected_item > span").text($('input[id$="ingredient"][value]').length.toString() + ' item(s) added')};
    $(function() {
        $('input[id$="ingredient"][value]').each(
            function() {
                    var sou = $("li.ingredient[value=" + $(this).attr('value') + "]");
                    sou.addClass('item-added');
                    var dst = $('input[id=' + this.id.replace("-ingredient", "-ingrdname") + ']');
                    if (dst.attr('value') == "") {dst.attr('value', sou.text());}
                });
        });
    });
</script>
{% endblock %}
{% block title %}Edit Recipe{% endblock %}
{% block content %}
<div id="header"><div id="headerimg"><div id="headertxt"><h1>Recipedia</h1>
<div id="desc">description</div>
</div></div></div>
<div id="page">
<div id="content" class="widecolumn"><div class="postpages">
<div class="entry"><h2 class="pagetitle">{% trans "Step 2: Compose your recipe" %}</h2>
    
    <h3>{{ recipe.name }}</h3>
    {% if recipe.thumb_photo %}<img src="{{ recipe.thumb_photo.url }}" alt="{{ recipe.name }}" width="{{ recipe.thumb_photo.width }}" height="{{ recipe.thumb_photo.height }}" />{% endif %}
<hr width="2">
{# <h2 id="counter"></h2> #}
<h4>{% trans "Choose Your Ingredient" %}</h4><h4>{% trans "You can pick an ingredient on left and drop on the list or " %}<a id="create-ingrd" href="#">{% trans "create yours." %}</a></h4>
{# <div>{{ ingrds.prefix }} {{ ingrds.initial_form_count}}</div> #}
<form method="post">{% csrf_token %}
{{ ingrds.management_form }}
<ul id='selected_item'><span>Selected Item</span></ul>
<input id='revert_selected_item' type="submit" value="Delete Selection">
<ol class="alt">{% if ingrds.forms.errors %}{{ ingrds.forms.errors }}{% endif %}
    {% for form in ingrds.forms %}
    <li>{% if form.errors %}{{ form.errors }}<br>{% endif %}
    {% if form.ingrdname.errors %}{{ form.ingrdname.label_tag }}{{ form.ingrdname.errors }}<br>{% endif %}
    {% if form.quantity.errors %}{{ form.quantity.label_tag }}{{ form.quantity.errors }}<br>{% endif %}
    {% if form.measure.errors %}{{ form.measure.label_tag }}{{ form.measure.errors }}<br>{% endif %}
    {{ form.id }}{{ form.recipe }}{{ form.ingredient}}
    {{ form.ingrdname.label_tag }} : {{ form.ingrdname }} {{ form.quantity.label_tag }} {{ form.quantity }} {{ form.measure }} {{ form.DELETE }}</li>
    {% endfor %}
</ol>
<p>{{ mthds.management_form }}
<table style="margin-left:3.5em;">
<tr><th>{% trans "Cooking Directions" %}</th><th>{% trans "Delete" %}</th></tr>    
{% if form.errors %}<tr colspan="2"><td>{{ form.errors }}</td></tr>{% endif %}{% for form in mthds.forms %}
<tr><td>{% if form.cookmethod.errors %}{{ form.cookmethod.errors }}<br>{% endif %}{{ form.cookmethod }}</td><td>{{ form.DELETE }}</td></tr>
{% endfor %}
</table></p>
<input type="submit" value="Post it!">
    <a class="button" style="margin-top: 0px; width: 200px;" href="">Test it</a>
</div>
</form>
</div></div>
{% include "footer.html" %}</div>
<span class="ui-helper-clearfix">{% regroup ingrdlist1 by category as ingrd_list %}
{% for category in ingrd_list %}
<div id="extruderLeft2" class="{title:'{{ category.grouper|make_list|join:" "  }}'} MbExtruder" >
    <ul id='{{ category.grouper }}'>
        {% for item in category.list %}
        <li class="ingredient" value="{{ item.id }}" data="{{ item.measure }}">{{ item.name }}</li>
        {% endfor %}
    </ul>
</div></span>
{% endfor %}
<script type="text/javascript" language="javascript">
	$(function() {
        //  setup dialog based on returned html content
        function setDialog(target, dlg) {
            var buttons = [];
            var login_url = "{% url django.contrib.auth.views.login %}?next=";
            var dst_url = "{% url add_ingredient_dlg %}";
            dlg.dialog( "option", "buttons", buttons ); //reset all buttons first
            if (target.find("input#id_username").length > 0) {
                dlg.dialog( "option", "title", "{% trans "User Login" %}");
                buttons.push({
                    text: "{% trans "login" %}",
                    click: function() {
                        var data = target.find("form").serialize();
                        $.post(login_url + dst_url, data, function(data) {
                            target.html(data);
                            setDialog(target, dlg);
                            });
                    }
                });
            }
            else if (target.find("input#id_measure").length > 0) {
                dlg.dialog( "option", "title", "{% trans "Create Ingredient" %}");
                buttons.push(
                    {
                        text: "{% trans "Create" %}",
                        click: function() {
                            var data = target.find("form").serialize();
                            $.post(dst_url, data, function(data) {
                                target.html(data);
                                setDialog(target, dlg);
                                });
                        }
                    });
            };
            buttons.push(
                {
                    text: "{% trans "Cancel" %}",
                    click: function() { dlg.dialog("close");} //; target.html("");}
                }
            );
            var dia = [dlg.dialog("option", "height"), dlg.dialog("option", "width")];
            dlg.dialog( "option", "buttons", buttons);
        };
        var dlg_param =
        // common configuration here
		{
			autoOpen: false,
			height: 300,
			width: 350,
			modal: true,
            close: function(event, ui) { $("#dialog-form").html(""); }
		};
        var dlg = $("#dialog-form").dialog(dlg_param);
		$( "#create-ingrd" )
//			.button()
			.click(function() {
                $("#dialog-form").load("{% url add_ingredient_dlg %}",
                function(e, xhr, settings) {
                    setDialog($("#dialog-form"), dlg);
                    dlg.dialog( "open" );
                });
                return false;
			});
	});
</script>
<div id="dialog-form"></div>
{% endblock %}

templates/footer.html
{% load i18n %}
<div id="footer">
    <p>
      Theme Preview is proudly powered by <a href="http://wordpress.org/">WordPress</a><br>
      <a title="web designer" href="http://www.brightcherry.co.uk">Web design</a> by Bright <b class="pink">Cherry</b>.<br>
      <h3>{% now "Y" %} {{ site }}{% trans " - All right reserved." %}</h3>
    </p>
</div>

templates/index.html
{% extends "basepage.html" %}
{% load i18n humanize customtag %}
{% block title %}{% trans "Welcome to " %}{{ site }}{% endblock %}
{% block head_script %}
    <script type="text/javascript" src="/scrp/jquery.js"></script>
    <script type="text/javascript" src="/scrp/jquery-ui.js"></script>
    <link type="text/css" href="{{ MEDIA_URL }}theme/ui-lightness/ui-lightness.css" rel="stylesheet" />
{% endblock %}
{% block content %}
<script type="text/javascript" language="javascript">
	$(function() {
        //  setup dialog based on returned html content
        function setDialog(target, dlg) {
            var buttons = [];
            var login_url = "{% url django.contrib.auth.views.login %}?next=";
            var dst_url = "{% url add_ingredient_dlg %}";
            dlg.dialog( "option", "buttons", buttons ); //reset all buttons first
            if (target.find("input#id_username").length > 0) {
                dlg.dialog( "option", "title", "{% trans "User Login" %}");
                buttons.push({
                    text: "{% trans "login" %}",
                    click: function() {
                        var data = target.find("form").serialize();
                        $.post(login_url + dst_url, data, function(data) {
                            target.html(data);
                            setDialog(target, dlg);
                            });
                    }
                });
            }
            else if (target.find("input#id_measure").length > 0) {
                dlg.dialog( "option", "title", "{% trans "Create Ingredient" %}");
                buttons.push(
                    {
                        text: "{% trans "Create" %}",
                        click: function() {
                            var data = target.find("form").serialize();
                            $.post(dst_url, data, function(data) {
                                target.html(data);
                                setDialog(target, dlg);
                                });
                        }
                    });
            };
            buttons.push(
                {
                    text: "{% trans "Cancel" %}",
                    click: function() { dlg.dialog("close");} //; target.html("");}
                }
            );
            var dia = [dlg.dialog("option", "height"), dlg.dialog("option", "width")];
            dlg.dialog( "option", "buttons", buttons);
        };
        var dlg_param =
        // common configuration here
		{
			autoOpen: false,
			height: 300,
			width: 350,
			modal: true,
            close: function(event, ui) { $("#dialog-form").html(""); }
		};
        var dlg = $("#dialog-form").dialog(dlg_param);
		$( "#create-user" )
			.button()
			.click(function() {
                $("#dialog-form").load("{% url add_ingredient_dlg %}",
                function(e, xhr, settings) {
                    setDialog($("#dialog-form"), dlg);
                    dlg.dialog( "open" );
                });

			});
	});
</script>
<div id="header"><div id="headerimg"><div id="headertxt"><h1>Recipedia</h1>
<div id="desc">description</div>
</div></div></div><div id="page">
<div id="content" class="narrowcolumn">
    {% with page.object_list as rp %}
    {% if rp %}<h2>{% trans "Latest Listings" %}</h2>{% for item in rp %}
        <div class="post">
          <div class="postindent">
            <h2>
              {% if item.thumb_photo %}<img class="alignleft" src="{{ item.thumb_photo.url }}" alt="{{ item.name }}" width="{{ item.thumb_photo.width }}" height="{{ item.thumb_photo.height }}" />{% endif %}<a href="{% url recipedia.views.view item.id %}">{{ item.name }}</a>
            </h2><div class="clear"></div>
            <div class="entry">
              <p>
                Boat.<p><a href="{% url recipedia.views.view item.id %}">{% trans "Read more..." %}</a>
              </p>{% if ismanage %}<table class="alt"><tr><td width="40px"><a href="{% url recipedia.views.create_edit item.id %}"><b class="pink">{% trans "Edit" %}</b></a></td><td><a href="{% url recipedia.views.delete item.id %}"><b class="pink">{% trans "Delete" %}</b></a></td></tr></table>{% endif %}
            </div>
            <div class="categorylink">{% trans "Category:" %} {% if item.tag %}{% for i in item.tag|split:"," %}<a href="{% url tag_search %}?n={{ i|iriencode }}">{{ i }}</a>{%if not forloop.last %}, {% endif %}{% endfor %}{% else %}{% trans "Uncategorized" %}{% endif %}</div>
            <div class="postmetadata">
              <div class="category">
                {{ item.createat|timesince }} <!-- by Theme Admin -->
              </div>
              <div class="comments">
                <span class="comments-link">{% trans "Recomment" %} {{ item.rating.rategoodcount|default:"0" }}</span>
              </div>
            </div>
          </div>
        </div>{% endfor %}
            {% else %}<p>{% trans "There is no any hit found. Post yours " %}<a href="">{% trans "here!" %}</a>.
            {% endif %}{% endwith %}
        {% if pagelist %}<p><table style="margin-left: 40px;"><tr>
        {% if page.has_previous %}<td width="10"><a href="{% url recipedia.views.index %}?sort={{ sort }};order={{ order }};page={{ page.previous_page_number }}">{% trans "Previous" %}</a></td>{% endif %}
        {% for i in pagelist %}<td width="20">{% if i != pagenum %}
            <a href="{% url recipedia.views.index %}?sort={{ sort }};order={{ order }};page={{ i }}">{{ i }}</a>
            {% else %}{{ i }}{% endif %}</td>{% endfor %}
        {% if page.has_next %}<td width="10"><a href="{% url recipedia.views.index %}?sort={{ sort }};order={{ order }};page={{ page.next_page_number }}">{% trans "Next" %}</a></td>{% endif %}</tr></table></p>{% endif %}            
        <button id="create-user">{% trans "Create Ingredient" %}</button>
        <div id="rightcol"></div>
</div>{% include "sidebar.html" %}{% include "footer.html" %}
</div>        <div id="dialog-form"></div>

{% endblock %}

templates/list.html
{% extends "basepage.html" %}
{% comment %}
  $Id$
{% endcomment %}
{% load i18n humanize %}
{% block title %}{{ site.name }} | {% endblock %}

{% block content %}
{% endblock %}

templates/login.html
{% extends "basepage.html" %}

{% block content %}
{% include "dialog/login.html" %}
{% comment %}
{% if form.errors %}
<p class="errorlist">Your username and password didn't match. Please try again.</p>
{% endif %}

<form method="post" action="#">{% csrf_token %}
 <table>
  <tr><th><label for="id_username">Username : </label></th><td>{{ form.username }}</td></tr>
  <tr><th><label for="id_password">Password : </label></th><td>{{ form.password }} <a href="">Forgot?</a></td></tr>
  <tr style="text-align: right;"><td colspan="2"><a href="">Register</a><input type="submit" value="Login" class="submit" /></td></tr>
 </table>
 <p>
   Note: By logging in, you agree to the<br /><a href="/termsofuse/" style="padding: 0px;" target="_blank" onclick="window.open('/termsofuse/basic/', 'Terms of Use', 'width=800,height=600,scrollbars=1'); return false;">Terms of Use</a> and <a href="/privacypolicy/" style="padding: 0px;" target="_blank" onclick="window.open('/privacypolicy/basic/', 'Privacy Policy', 'width=800,height=600,scrollbars=1'); return false;">Privacy Policy</a>.
  <input type="hidden" name="next" value="{{ next }}" />
 </p>
</form>
{% endcomment %}
{% endblock %}

templates/new_ingredient.html
{% extends "basepage.html" %}
{% load i18n %}
{% block page_meta %}{{ form.media|safe }}{% endblock %}
{% block title %}Test 3{% endblock %}
{% block content %}
<div id="header"><div id="headerimg"><div id="headertxt"><h1>Recipedia</h1>
<div id="desc">description</div>
</div></div></div><div id="page">
<div id="content" class="narrowcolumn"><div class="postpages">
<div class="entry"><h2>{% trans "Create Ingredient" %}</h2><p></p>
<form enctype="multipart/form-data" method="post">{% csrf_token %}
<table>
<tr>
   <th class="th-left">{{ form.name.label_tag }} : <br><div class="helptext">{{ form.name.help_text }}</div></th>
   <td colspan="3">
    {% if form.name.errors %}<ul class="errorlist">{{ form.name.errors }}</ul>{% endif %}
    {{ form.name }}
    {% if form.name.field.required %}require<img src="{{ MEDIA_URL }}images/required.png" alt="Required" width="8" height="8" />{% endif %}
   </td>
  </tr>
<tr>
<tr>
   <th class="th-left">{{ form.measure.label_tag }} : <br><div class="helptext">{{ form.measure.help_text }}</div></th>
   <td colspan="3">
    {% if form.measure.errors %}<ul class="errorlist">{{ form.measure.errors }}</ul>{% endif %}
    {{ form.measure }}
    {% if form.measure.field.required %}require<img src="{{ MEDIA_URL }}images/required.png" alt="Required" width="8" height="8" />{% endif %}
   </td>
  </tr>
<tr>
<tr>
   <th class="th-left">{{ form.category.label_tag }} : <br><div class="helptext">{{ form.category.help_text }}</div></th>
   <td colspan="3">
    {% if form.category.errors %}<ul class="errorlist">{{ form.category.errors }}</ul>{% endif %}
    {{ form.category }}
    {% if form.category.field.required %}require<img src="{{ MEDIA_URL }}images/required.png" alt="Required" width="8" height="8" />{% endif %}
   </td>
  </tr>
<tr>
<tr>
   <th class="th-left">{{ form.full_photo.label_tag }} : <br><div class="helptext">{{ form.full_photo.help_text }}</div></th>
   <td colspan="3">
    {% if form.full_photo.errors %}<ul class="errorlist">{{ form.full_photo.errors }}</ul>{% endif %}
    {{ form.full_photo }}
    {% if form.full_photo.field.required %}require<img src="{{ MEDIA_URL }}images/required.png" alt="Required" width="8" height="8" />{% endif %}
   </td>
  </tr>
<tr>
<tr>
   <th class="th-left">{{ form.thumb_photo.label_tag }} : <br><div class="helptext">{{ form.thumb_photo.help_text }}</div></th>
   <td colspan="3">
    {% if form.thumb_photo.errors %}<ul class="errorlist">{{ form.thumb_photo.errors }}</ul>{% endif %}
    {{ form.thumb_photo }}
    {% if form.thumb_photo.field.required %}require<img src="{{ MEDIA_URL }}images/required.png" alt="Required" width="8" height="8" />{% endif %}
   </td>
  </tr>
<tr>
</table>
    <a class="button" style="margin-top: 0px; width: 200px;" href="">Test it</a>
  <input type="submit" class="submit" value="{% if create %}Create{% else %}Update{% endif %}" />
</form>
</div></div></div>{% include "sidebar.html" %}{% include "footer.html" %}</div>
{% endblock %}